// <auto-generated />
using System;
using CarPoolDbContext.CarpoolData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarPoolAPI.Migrations
{
    [DbContext(typeof(CarPoolDataDbContext))]
    [Migration("20230427071626_New-Migration")]
    partial class NewMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarPoolModels.Models.BookedRide", b =>
                {
                    b.Property<Guid>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BookedFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BookedSeats")
                        .HasColumnType("int");

                    b.Property<string>("BookedTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<Guid>("RideOfferedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RideTakenBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.ToTable("BookedRides");
                });

            modelBuilder.Entity("CarPoolModels.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("LocationName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("CarPoolModels.Models.OfferedRide", b =>
                {
                    b.Property<Guid>("OfferedRideId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<Guid?>("OfferedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OfferingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OfferingFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfferingTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.HasKey("OfferedRideId");

                    b.HasIndex("OfferedBy");

                    b.ToTable("OfferedRides");
                });

            modelBuilder.Entity("CarPoolModels.Models.Stoppage", b =>
                {
                    b.Property<int>("StoppageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoppageId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OfferedRideId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("StoppageId");

                    b.HasIndex("OfferedRideId");

                    b.ToTable("Stoppages");
                });

            modelBuilder.Entity("CarPoolModels.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CarPoolModels.Models.OfferedRide", b =>
                {
                    b.HasOne("CarPoolModels.Models.User", "Users")
                        .WithMany()
                        .HasForeignKey("OfferedBy");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CarPoolModels.Models.Stoppage", b =>
                {
                    b.HasOne("CarPoolModels.Models.OfferedRide", "OfferedRides")
                        .WithMany()
                        .HasForeignKey("OfferedRideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OfferedRides");
                });
#pragma warning restore 612, 618
        }
    }
}
